//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderEntry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colorway
    {
        public string CWAY1 { get; set; }
        public string DESNO { get; set; }
        public string DESNA { get; set; }
        public string CWAYNO { get; set; }
        public Nullable<double> CWNUM { get; set; }
        public Nullable<double> CNOCYLS { get; set; }
        public string SUBNO { get; set; }
        public string PTYPE { get; set; }
        public string PWIDTH { get; set; }
        public string PWEIGHT { get; set; }
        public string MKTNO { get; set; }
        public string MARKET { get; set; }
        public string CLRDSCD1 { get; set; }
        public string CLRDSCD2 { get; set; }
        public string CLRDSCD3 { get; set; }
        public string COLOR { get; set; }
        public Nullable<double> CLEAN { get; set; }
        public string INKFOR1 { get; set; }
        public string INKFOR2 { get; set; }
        public string INKFOR3 { get; set; }
        public string INKFOR4 { get; set; }
        public string INKFOR5 { get; set; }
        public string INKFOR6 { get; set; }
        public string INKFOR7 { get; set; }
        public string INKFOR8 { get; set; }
        public string INKFOR9 { get; set; }
        public string INKFOR10 { get; set; }
        public string INKNO1 { get; set; }
        public string INKNO2 { get; set; }
        public string INKNO3 { get; set; }
        public string INKNO4 { get; set; }
        public string INKNO5 { get; set; }
        public string INKNO6 { get; set; }
        public string INKNO7 { get; set; }
        public string INKNO8 { get; set; }
        public string INKNO9 { get; set; }
        public string INKNO10 { get; set; }
        public string CYLNO1 { get; set; }
        public string CYLNO2 { get; set; }
        public string CYLNO3 { get; set; }
        public string CYLNO4 { get; set; }
        public string CYLNO5 { get; set; }
        public string CYLNO6 { get; set; }
        public string CYLNO7 { get; set; }
        public string CYLNO8 { get; set; }
        public string CYLNO9 { get; set; }
        public string CYLNO10 { get; set; }
        public Nullable<System.DateTime> CPDATE { get; set; }
        public Nullable<System.DateTime> LASTPRT { get; set; }
        public Nullable<System.DateTime> LASTPRF { get; set; }
        public string ORIG__CUST { get; set; }
        public string CWSTAT { get; set; }
        public Nullable<System.DateTime> DOFF { get; set; }
        public string REFERENCE { get; set; }
        public string HARDPROOF { get; set; }
        public string NEWCWAY { get; set; }
        public string FUTURE1 { get; set; }
    }
}
