//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderEntry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public double CUSTNO { get; set; }
        public string CUSTNA { get; set; }
        public string CBADR1 { get; set; }
        public string CBADR2 { get; set; }
        public string CBADR3 { get; set; }
        public string CBCITY { get; set; }
        public string CBST { get; set; }
        public string CBZIP { get; set; }
        public string CNTRYNO { get; set; }
        public string COUNTRY { get; set; }
        public string CBPHONE { get; set; }
        public string CBFAX { get; set; }
        public string CBFEDEX { get; set; }
        public string CSNAME { get; set; }
        public string CSADR1 { get; set; }
        public string CSADR2 { get; set; }
        public string CSADR3 { get; set; }
        public string CSCITY { get; set; }
        public string CSST { get; set; }
        public string CSZIP { get; set; }
        public string CSCOUNTRY { get; set; }
        public string CSATTN { get; set; }
        public string CSSADR1 { get; set; }
        public string CSSADR2 { get; set; }
        public string CSSADR3 { get; set; }
        public string CSSCITY { get; set; }
        public string CSSST { get; set; }
        public string CSSZIP { get; set; }
        public string CSSCOUNTRY { get; set; }
        public string CSSATTN { get; set; }
        public string TERMNO { get; set; }
        public string TERMS { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<double> CLIMIT { get; set; }
        public Nullable<System.DateTime> LPROOF { get; set; }
        public string SPERSON1 { get; set; }
        public string SNAME1 { get; set; }
        public string SPERSON2 { get; set; }
        public string SNAME2 { get; set; }
        public string MARKET { get; set; }
        public string SHIP_METH { get; set; }
        public string SAMPLE_SHIP_VIA { get; set; }
        public string SAMPLE_SHIP_METH { get; set; }
        public string SHIP_COMMENT { get; set; }
        public string SALES_DIRECTOR { get; set; }
        public string FAX_TO_AGENT { get; set; }
        public string FAX_TO_CUST { get; set; }
        public string FAX_TO_DIRECTOR { get; set; }
        public string FAX_ATTN { get; set; }
        public string AR_CONTACT1 { get; set; }
        public string AR_CONTACT2 { get; set; }
        public string AR_PHONE { get; set; }
        public string AR_FAX { get; set; }
        public string AR_NOTES { get; set; }
        public string VAT { get; set; }
    }
}
