//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderEntry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Design
    {
        public string DESNO { get; set; }
        public string DESNA { get; set; }
        public Nullable<double> HREPEAT { get; set; }
        public Nullable<double> VREPEAT { get; set; }
        public string REPEATDESC { get; set; }
        public string SUBNO { get; set; }
        public string PTYPE { get; set; }
        public string PWIDTH { get; set; }
        public string PWEIGHT { get; set; }
        public Nullable<double> CYLSIZE { get; set; }
        public string ENDS { get; set; }
        public string PATNO1 { get; set; }
        public string PATNO2 { get; set; }
        public string PATNO3 { get; set; }
        public string PATNO4 { get; set; }
        public string INGR { get; set; }
        public Nullable<double> CNOCYLS { get; set; }
        public string DRSTR { get; set; }
        public string CUSTNAME { get; set; }
        public Nullable<System.DateTime> DAVAIL { get; set; }
        public Nullable<System.DateTime> DOFF { get; set; }
        public string DJUGGLE { get; set; }
        public string DPARENT1 { get; set; }
        public string DPARENT2 { get; set; }
        public string DPARENT3 { get; set; }
        public string DPARENT4 { get; set; }
        public Nullable<double> NXTCWNO { get; set; }
        public string CYLNO1 { get; set; }
        public string CYLNO2 { get; set; }
        public string CYLNO3 { get; set; }
        public string CYLNO4 { get; set; }
        public string CYLNO5 { get; set; }
        public string CYLNO6 { get; set; }
        public string CYLNO7 { get; set; }
        public string CYLNO8 { get; set; }
        public string CYLNO9 { get; set; }
        public string CYLNO10 { get; set; }
        public Nullable<System.DateTime> LASTPRF { get; set; }
        public Nullable<System.DateTime> LASTPRNT { get; set; }
        public string DESCR { get; set; }
        public string HARDPRF { get; set; }
        public string NOTES { get; set; }
        public Nullable<double> TRANSWIDE_MAX_WIDTH { get; set; }
        public Nullable<double> DDS_WIDTH { get; set; }
        public Nullable<double> V_REPEAT { get; set; }
        public Nullable<System.DateTime> DEXPIRE { get; set; }
    }
}
