//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderEntry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineItem
    {
        public string OrderID { get; set; }
        public double LINENO { get; set; }
        public string CWAY { get; set; }
        public string DESNO { get; set; }
        public string DESNA { get; set; }
        public string CITEM { get; set; }
        public string CWAYNO { get; set; }
        public string COLORNO { get; set; }
        public string COLOR { get; set; }
        public string SUBNO { get; set; }
        public string PTYPE { get; set; }
        public string PWIDTH { get; set; }
        public string PWEIGHT { get; set; }
        public Nullable<double> TNUMBER { get; set; }
        public string TNOCWAY { get; set; }
        public string MCHINECD { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string SPLICE { get; set; }
        public Nullable<double> SPLICE_PRICE { get; set; }
        public Nullable<double> SPLICE_QTY { get; set; }
        public Nullable<double> SPLICE_WIDTH { get; set; }
        public Nullable<double> OQTY { get; set; }
        public Nullable<double> JEMTRS { get; set; }
        public Nullable<double> JEMTRS_SPLICED { get; set; }
        public Nullable<double> BILLEDM { get; set; }
        public Nullable<double> TOBILLM { get; set; }
        public Nullable<double> LABMTRS { get; set; }
        public Nullable<double> EXTPRICE { get; set; }
        public string ODNOTE { get; set; }
        public string ODSTAT { get; set; }
        public Nullable<double> CNOCYLS { get; set; }
        public Nullable<double> INVNO { get; set; }
        public Nullable<System.DateTime> DOFF { get; set; }
        public string CUSTNAME { get; set; }
        public string REMARKS_DES_CUST { get; set; }
        public Nullable<double> JE_Index { get; set; }
    }
}
