//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderEntry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPerson
    {
        public SalesPerson()
        {
            this.SalesPerson1 = new HashSet<SalesPerson>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public Nullable<int> SalesDirector { get; set; }
    
        public virtual ICollection<SalesPerson> SalesPerson1 { get; set; }
        public virtual SalesPerson SalesPerson2 { get; set; }
    }
}
