CREATE TABLE [dbo].[LineItem](
	[OrderID] [varchar](9) NOT NULL,
	[LINENO] [float] NOT NULL,
	[CWAY] [varchar](14) NULL,
	[DESNO] [varchar](7) NULL,
	[DESNA] [varchar](30) NULL,
	[CITEM] [varchar](30) NULL,
	[CWAYNO] [varchar](6) NULL,
	[COLORNO] [varchar](2) NULL,
	[COLOR] [varchar](15) NULL,
	[SUBNO] [varchar](2) NULL,
	[PTYPE] [varchar](15) NULL,
	[PWIDTH] [varchar](2) NULL,
	[PWEIGHT] [varchar](2) NULL,
	[TNUMBER] [float] NULL,
	[TNOCWAY] [varchar](21) NULL,
	[MCHINECD] [varchar](2) NULL,
	[PRICE] [float] NULL,
	[SPLICE] [varchar](2) NULL,
	[SPLICE_PRICE] [float] NULL,
	[SPLICE_QTY] [float] NULL,
	[SPLICE_WIDTH] [float] NULL,
	[OQTY] [float] NULL,
	[JEMTRS] [float] NULL,
	[JEMTRS_SPLICED] [float] NULL,
	[BILLEDM] [float] NULL,
	[TOBILLM] [float] NULL,
	[LABMTRS] [float] NULL,
	[EXTPRICE] [float] NULL,
	[ODNOTE] [varchar](1) NULL,
	[ODSTAT] [varchar](15) NULL,
	[CNOCYLS] [float] NULL,
	[INVNO] [float] NULL,
	[DOFF] [datetime] NULL,
	[CUSTNAME] [varchar](31) NULL,
	[REMARKS_DES_CUST] [varchar](100) NULL,
	[JE_Index] [float] NULL, 
    CONSTRAINT [PK_LineItem] PRIMARY KEY ([OrderID],[LINENO])
) 


