CREATE TABLE [dbo].[Order](
	[ID] UNIQUEIDENTIFIER NOT NULL,
	[ODATE] [datetime] NULL,
	[SDATE] [datetime] NULL,
	[CUSTNO] [float] NULL,
	[CUSTNA] [varchar](30) NULL,
	[CORDNO] [varchar](30) NULL,
	[OSTATUS] [varchar](1) NULL,
	[SPERSON1] [varchar](3) NULL,
	[SNAME1] [varchar](20) NULL,
	[SPERSON2] [varchar](3) NULL,
	[SNAME2] [varchar](20) NULL,
	[CBADR1] [varchar](25) NULL,
	[CBADR2] [varchar](25) NULL,
	[CBADR3] [varchar](25) NULL,
	[CBCITY] [varchar](20) NULL,
	[CBST] [varchar](2) NULL,
	[CBZIP] [varchar](10) NULL,
	[CNTRYNO] [varchar](2) NULL,
	[COUNTRY] [varchar](20) NULL,
	[CBPHONE] [varchar](16) NULL,
	[CSNAME] [varchar](25) NULL,
	[CSADR1] [varchar](25) NULL,
	[CSADR2] [varchar](25) NULL,
	[CSADR3] [varchar](25) NULL,
	[CSCITY] [varchar](20) NULL,
	[CSST] [varchar](2) NULL,
	[CSZIP] [varchar](10) NULL,
	[CSCOUNTRY] [varchar](20) NULL,
	[CSATTN] [varchar](20) NULL,
	[XPORT] [varchar](2) NULL,
	[XRATE] [float] NULL,
	[TERMNO] [varchar](2) NULL,
	[TERMS] [varchar](20) NULL,
	[CURRENCY] [varchar](14) NULL,
	[LABPRT] [varchar](2) NULL,
	[OCONPRT] [varchar](2) NULL,
	[OHSTATUS] [varchar](15) NULL,
	[REMARKS] [varchar](500) NULL,
	[DELIVERY TERMS] [varchar](30) NULL,
	[SHIP VIA] [varchar](35) NULL,
	[MARKET] [varchar](20) NULL,
	[OFFICE_REMARKS] [varchar](500) NULL,
	[NOT_BEFORE] [datetime] NULL,
	[AUTHORIZATION] [varchar](15) NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
))



